heat_template_version: 2016-04-08

description: >
  OpenStack Glance Registry service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MysqlVirtualIPUri:
    type: string
    default: ''

resources:

  GlanceRegistryBase:
    type: ../glance-registry.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      MysqlVirtualIPUri: {get_param: MysqlVirtualIPUri}

outputs:
  role_data:
    description: Role data for the Glance role.
    value:
      config_settings:
        get_attr: [GlanceRegistryBase, role_data, config_settings]
      # No puppet manifests since glance-registry is included in
      # ::tripleo::profile::pacemaker::glance which is maintained alongside of
      # pacemaker/glance-api.yaml.
      step_config:
