heat_template_version: 2015-10-15

description: Configure hieradata for Controllers with the lightweight architecture

parameters:
  server:
    description: ID of the controller node to apply this config to
    type: string

  # Config specific parameters, to be provided via parameter_defaults
  ControllerLightKeystoneDbMaxRetries:
    type: number
    default: -1
  ControllerLightGlanceApiDbMaxRetries:
    type: number
    default: -1
  ControllerLightGlanceRegistryDbMaxRetries:
    type: number
    default: -1
  ControllerLightNovaDbMaxRetries:
    type: number
    default: -1
  ControllerLightCinderDbMaxRetries:
    type: number
    default: -1
  ControllerLightHeatDbMaxRetries:
    type: number
    default: -1
  ControllerLightNeutronDbMaxRetries:
    type: number
    default: -1
  ControllerLightSaharaDbMaxRetries:
    type: number
    default: -1
  ControllerLightAodhDbMaxRetries:
    type: number
    default: -1
  ControllerLightCeilometerDbMaxRetries:
    type: number
    default: -1
  ControllerLightManilaDbMaxRetries:
    type: number
    default: -1

resources:
  ControllerLightConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          datafiles:
            controller_lightweight:
              mapped_data:
                keystone::database_max_retries: {get_input: KeystoneDbMaxRetries}
                glance::api::database_max_retries: {get_input: GlanceApiDbMaxRetries}
                glance::registry::database_max_retries: {get_input: GlanceRegistryDbMaxRetries}
                nova::database_max_retries: {get_input: NovaDbMaxRetries}
                cinder::database_max_retries: {get_input: CinderDbMaxRetries}
                heat::database_max_retries: {get_input: HeatDbMaxRetries}
                neutron::server::database_max_retries: {get_input: NeutronDbMaxRetries}
                sahara::database_max_retries: {get_input: SaharaDbMaxRetries}
                aodh::database_max_retries: {get_input: AodhDbMaxRetries}
                ceilometer::db::database_max_retries: {get_input: CeilometerDbMaxRetries}
                manila::database_max_retries: {get_input: ManilaDbMaxRetries}

  ControllerLightDeployment:
    type: OS::Heat::StructuredDeployment
    properties:
      config: {get_resource: ControllerLightConfig}
      server: {get_param: server}
      input_values:
        KeystoneDbMaxRetries: {get_param: ControllerLightKeystoneDbMaxRetries}
        GlanceApiDbMaxRetries: {get_param: ControllerLightGlanceApiDbMaxRetries}
        GlanceRegistryDbMaxRetries: {get_param: ControllerLightGlanceRegistryDbMaxRetries}
        NovaDbMaxRetries: {get_param: ControllerLightNovaDbMaxRetries}
        CinderDbMaxRetries: {get_param: ControllerLightCinderDbMaxRetries}
        HeatDbMaxRetries: {get_param: ControllerLightHeatDbMaxRetries}
        NeutronDbMaxRetries: {get_param: ControllerLightNeutronDbMaxRetries}
        SaharaDbMaxRetries: {get_param: ControllerLightSaharaDbMaxRetries}
        AodhDbMaxRetries: {get_param: ControllerLightAodhDbMaxRetries}
        CeilometerDbMaxRetries: {get_param: ControllerLightCeilometerDbMaxRetries}
        ManilaDbMaxRetries: {get_param: ControllerLightManilaDbMaxRetries}

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger puppet apply on changes
    value: {get_attr: [ControllerLightDeployment, deploy_stdout]}
